name: 'github-action-build'
description: 'Build a project, creating artifacts'
branding:
  icon: settings
  color: black
inputs:
  builder:
    description: 'The path to the build-script to run, within the repository.'
    default: '.github/build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.builder }}
